### ISSUE TITLE
[RFC] Support for NATS

### ISSUE THREAD

**Issue by haozige90** [spiral/roadrunner-plugins#24]
Hi guys, 

Thanks for great job, we have run RR in production for months, so far so good.

We are trying to use nats for async service communication, and we decide to use nats golang client.

Reasons:
1. As you mentioned in Spiral doc, due to the blocking nature of PHP.
2. Nats PHP client is unofficial, and it has no good support from community.

May I know do you have any suggestions for us?

**Comment by rustatian** [comment]
@sash2222 Could you please explain, what is your expectations from the NATS driver in the RR? Do you need to subscribe to the particular message, or it would be enough to subscribe to `*`, in the RR, but have the ability to push to a particular topic?
Because from my perspective, we can have 1 subscriber in the RR with a pattern like `roadrunner-*`, and you'd have the ability to push to any topic (including `roadrunner-*`).

**Comment by rustatian** [comment]
```php
$queue = $jobs->create(new MemoryCreateInfo(
    name: 'example',
    priority: 42,
    prefetch: 10,
));
```
This is how to create an In-Memory pipeline in the runtime for example.
See: https://roadrunner.dev/docs/beep-beep-jobs (will be populated with NATS when it's ready).

**Comment by sash2222** [comment]
planned JS but in principle NATS might be fine too.

**Comment by rustatian** [comment]
RR2 will support only JS as the initial NATS implementation.

**Comment by rustatian** [comment]
@sash2222 Just to be on the same page. The worker at the moment can't respond to the request (in terms of the NATS responses). So, RR will listen to the subject/stream and pass the messages to the worker. And also manage NATS ACK/NAK. But at the moment, responses from the JOB worker are not possible.

**Comment by rustatian** [comment]
> Then would a request-response pattern be possible (https://docs.nats.io/nats-concepts/reqreply)?

Yes

> PHP will receive a message with the subject of the response from RR

Yeah, you can put in the Job payload (or better headers) whatever you want :)

> Something like this?

Yeah. You have to specify the driver for the response and subject for the NATS.

```json
type : Response

// response payload
driver: nats (string)

// nats specific options
subject: foo (string)
```
Then your message *body* will be pushed as the response. Smt like that.

**Comment by rustatian** [comment]
So, as the summary:
1. response context -> protocol.
2. response body -> your payload to respond.

I'll write documentation for that and send you a link.
