### ISSUE TITLE
[FEATURE REQUEST] Access logs

### ISSUE THREAD

**Issue by cidious** [spiral/roadrunner-plugins#34]
The problem is I can't find the access logs when running RR as a frontend web server for PHP Laravel app.

When running the app as Nginx+PHP-FPM you got the access logs from nginx plus slow logs from FPM. Both of them can be routed to stderr inside a container and caught for analysis.

I see the two options to get the logs using RR:

- run RR in debug mode. You got a lot more logging than the access logs. It can affect the performance.
- create the logs with Laravel logger. It should affect the performance plus increase the TTFB (time to first byte) lowering the server responsiveness. Plus it cannot log the static files.

Is it possible to output the access logs by RR in production env?

**Comment by rustatian** [comment]
@cidious Feature will be available by the end of the week in the `v2.5.0-beta.2` with the following fields:
`method` - http method.
`remote_addr` - request remote address.
`bytes_sent` - content-length,
`http_host` - host.
`request` - request Query.
`time_local` - local time in Common Log Format.
`request_length` - request body with headers size (content-len + size of all headers) in bytes. Max allowed headers size for the RR is 1MB.
`request_time` - request processing time in seconds with a milliseconds resolution.
`status` - http response status.
`http_user_agent` - http user [agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent)
`http_referer` - http [referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer)
