### ISSUE TITLE
[FEATURE REQUEST] Support X-Sendfile Header

### ISSUE THREAD

**Issue by alexander-schranz** [spiral/roadrunner-plugins#9]
**Is your feature request related to a problem? Please describe.**

When having private files behind a PHP firewall you return them in Symfony as a BinaryFileResponse. When supported by the Webserver in this case the `x-sendfile` header will be used which just tell the webserver where the file can be found which need to be streamed out.

**Describe the solution you'd like**

It would be great when roadrunner would also support the x-sendfile header. I could not yet find a reference or a config how this kind of response are handled in roadrunner.

**Describe alternatives you've considered**

Alternative is not supporting `x-sendfile` Symfony does then fallback to a normal file stream to php://output.

**Additional context**

Apache does support x-sendfile of the sendfile mod. Nginx I think does support it out of the box. The state of caddy webserver I don't know.

**Comment by rustatian** [comment]
@alexander-schranz Feature will be available for testing by the end of the week in the `v2.5.0-beta.2`.

**Comment by alexander-schranz** [comment]
Awesome thank you all 👍
